export const ROUTES = {
  HOME: '/',
  ABOUT: '/sobre',
  SERVICES: '/servicos',
  SERVICE_OPENING: '/servicos/abertura-empresas',
  SERVICE_MEI: '/servicos/contabilidade-mei',
  SERVICE_CONSULTING: '/servicos/consultoria-contabil',
  SERVICE_IR: '/servicos/declaracao-ir',
  SERVICE_REGULARIZATION: '/servicos/regularizacao-empresas',
  SERVICE_SMALL_BUSINESS: '/servicos/contabilidade-pequenas-empresas',
  BLOG: '/blog',
  BLOG_POST: '/blog/:slug',
  CONTACT: '/contato',
  CLIENT_AREA: '/area-cliente',
  PRIVACY_POLICY: '/politica-privacidade',
  // Rotas do painel administrativo
  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_BLOG: '/admin/blog',
  ADMIN_BLOG_NEW: '/admin/blog/novo',
  ADMIN_BLOG_EDIT: '/admin/blog/editar/:id',
  ADMIN_BLOG_CATEGORIES: '/admin/blog/categorias',
  ADMIN_BLOG_TAGS: '/admin/blog/tags',
  ADMIN_NEWSLETTER: '/admin/newsletter'
}; 